export const MASTER_SERVICIOS_SOCIALES = [
  "Batucada de bienvenida",
  "Camerino (vestidor) privado",
  "Mesa principal decorada con arco de follaje y flores",
  "Mesas redondas y sillas tiffany acojinadas",
  "Mantelería selecta y montaje de gala",
  "Planeador y coordinador de evento profesional",
  "Dj con música mezclada durante todo el evento",
  "Luces audiorítmicas (robóticas) profesionales",
  "Pista de cristal iluminada",
  "Pantalla gigante para proyección de videos",
  "Área de juegos con personal para la supervisión de los niños",
  "Capitán de meseros (maestro de ceremonias) y personal de meseros",
  "Personal para el cuidado de sus autos (cuota sugerida)",
  "Invitaciones digitales personalizadas",
  "2 vitroleros de agua de sabor a elegir",
  "Amenización de comida con saxofonista, violinista o baile folklórico",
  "Vasos, plaque y loza elegante",
  "Refresco, agua mineral y hielo ilimitado durante el evento",
  "Servicio de Bar (Bar service)",
  "Batucada de cierre (con globos salchicha y lluvia de papelitos de colores) y amenización del pastel",
  "Servicio de cámara 360° durante 2 horas",
  "Álbum digital en USB (con más de 150 archivos fotográficos)",
  "Álbum impreso de alta calidad",
  "Tornamesa de chilaquiles o pozole para el cierre de evento",
  "Grupo versátil musical en vivo durante 2 horas"
];

export const MASTER_SERVICIOS_INFANTILES = [
  "Servicio de salón privado con áreas limpias",
  "Juegos (Castillo de princesas, futbolito, alberca de pelotas, resbaladilla, tobogán, brincolín)",
  "Mesas con sillas infantiles y mesas de adultos con manteles de color a elegir",
  "Espectacular bienvenida con un regalo luminoso y mini batucada con personaje exclusivo (Mickey, Donald, Minnie, Goofy, Toy Story, Princesas, Super Héroes, Paw Patrol, etc.)",
  "Coordinación y amenización del evento con Dj como maestro de ceremonias",
  "Luces audio rítmicas espectaculares",
  "Música mezclada durante todo el evento (infantil, ambiental, bailable)",
  "Juegos y dinámicas organizadas para niños y adultos",
  "Pantalla gigante para videos musicales y películas infantiles",
  "Personal mixto para organización (meseros y nana de apoyo para supervisión)",
  "Espectacular batucada con lluvia de papeles de colores y globos",
  "Área de juegos con personal dedicado",
  "Acceso y uso libre de cocina",
  "Invitaciones y boletos digitales de cortesía",
  "Foto familiar conmemorativa del evento",
  "Refresco y hielo ilimitado durante todo el evento",
  "Dos vitroleros de agua fresca de sabor a elegir",
  "Ideal para papás que quieren descansar y disfrutar el banquete completo",
  "Piñata completa con dulces y regalos del salón",
  "Espectacular Show Fantasy con personajes y dinámicas exclusivas",
  "Piñata completa de dulces y regalos de primera",
  "Espectacular Show Fantasy con personajes",
  "Cristalería elegante incluida",
  "Video USB con la reseña completa del evento",
  "Mesa de dulces decorada temática para niños"
];
